version: "3.3"
services: 
  web:
    build: ./Product
    command: gunicorn Product.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./Product/:/crm/
    expose: 
      - 8000
    depends_on: 
      - db
  db:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    expose: 
      - '3306'
    environment: 
      MYSQL_DATABASE: 'djangodatabase'
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    restart: always
    volumes: 
      - ./Product/db_django:/var/lib/mysql
  nginx:
    build: ./nginx
    volumes: 
      - ./Product/static:/var/static
    ports:
      - 80:80
    restart: always
    depends_on: 
      - web

volumes: 
  static_volume: