version: "3.3"

services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/web_django
    ports: 
      - '8000:8000'
    depends_on: 
      - db
  db:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    expose: 
      - '3306'
    environment: 
      MYSQL_DATABASE: 'djangodatabase'
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    restart: always
    volumes: 
      - ./db_django:/var/lib/mysql